### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by dukesrg** [dukesrg/rxTools#20]
- [x] English - The basic and builtin
- [x] French @mariogamer2 
- [ ] Italian
- [ ] German @hartmannaf
- [ ] Spanish  - WIP @Sinon-AnnaTheFurry
- [x] Russain - WIP @dukesrg
- [ ] Chinese - partly blocked by #14
- [ ] Chinese(Taiwan) - partly blocked by #14
- [ ] Korean - blocked by #14

**Comment by mariogamer2** [comment]
I can help with french, but what do you mean by translate? There is already file...not totally translated?

**Comment by Hartie95** [comment]
I could help with German.

**Comment by dukesrg** [comment]
@mariogamer2 that file contains old strings mostly incompatible with the new version. You could refer to ru.json, I've just added most of the updated strings there.

**Comment by mariogamer2** [comment]
@dukesrg Does it is normal that en.json is smaller than ru.json?

For now, I'll copy ru.json content and translate it.

**Comment by mariogamer2** [comment]
Does "ï" is printable?

Just pushed an Initial translate,I didn't complete it at all. I'll do it soon _**TM**_

**Comment by dukesrg** [comment]
@mariogamer2 en.json actually will have button translation to unicode special characters representing button glyphs in Nintendo form.
Font seems to have full latin character sets, so this character should be printable too.

**Comment by Hartie95** [comment]
There are some strings inside of the ru.json that could maybe merged to strings with params, (something like "Copy Emunand1 to Sysnand", "Copy Emunand2 to Sysnand", "copy Sysnand to Emunand1" could be something like "Copy %s to %s" and instead of "Emunandx" it could be "Emunand%i"
This would make translating a bit easier, because it would not be that often the same.

**Comment by dukesrg** [comment]
@hartmannaf I know, those strings are from GUI.json and intensionally left with no parameters since it would increase json parser complexity. Strings builtin into the code are using parameters, strings inside GUI.json just plain.

**Comment by mariogamer2** [comment]
Does "é" "è" and other are supported?

**Comment by dukesrg** [comment]
Yes, it is! All the symbols you could probably see in native 3DS  interface :)

**Comment by mariogamer2** [comment]
Why "native" ?

**Comment by dukesrg** [comment]
mariogamer2:
Because this is a built-in font of 3DS, so any unicode character you encounter in 3DS interface is available here to. You can use full latin character set, write in french with no limits :)

**Comment by mariogamer2** [comment]
I probably need help with some technical word....

@motezazer Can you verify me when I'll finish the translate? I'll  let you edit my repo soon (**_TM_** XD)

**Comment by mariogamer2** [comment]
This will be good to implement a new language format,to be able to remove lot of strings (language file are very long...)

**Comment by dukesrg** [comment]
@mariogamer2 GUI file is actually longer then 200 kB and it is still works fine! Making parameter strings will result GUI parser more complicated and inavoidable mistakes with translation to different languages. Translation routine also converts from 8bit to wide char at the same time, so we just can't resolve several nested parameters in a row, like Copy %ls whereas ls% is substituted by EmuNAND%u. Built in strings are with parameters so no space wasted. However we can issue a feature request for that.

**Comment by mariogamer2** [comment]
Hu? https://github.com/dukesrg/rxTools/blob/master/lang/ru.json#L137  There is two first and two second, why?

**Comment by dukesrg** [comment]
Copy -paste typo, must be only once, fix it

**Comment by dukesrg** [comment]
@hartmannaf @Sinon-AnnaTheFurry could you also update translations?

**Comment by mariogamer2** [comment]
They probably wait to push everythings in a block,not like me :D .

P.S. What is BCFNT ?
